apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  namespace: edu-naughty-cray
  labels:
    env: dev
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: olgazhivaeva/django-site:c626cdb
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: dsn
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: ALLOWED_HOSTS
        volumeMounts:
        - name: pg-root-cert
          mountPath: /usr/local/share/ca-certificates/
          readOnly: true
      volumes:
      - name: pg-root-cert
        secret:
          secretName: pg-root-cert
          defaultMode: 384