apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cronjob
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: django-clearsessions-container
            image: django_app
            imagePullPolicy: IfNotPresent
            command: ["python3", "manage.py", "clearsessions"]
            envFrom:
            - secretRef:
                name: django-secrets