apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: edu-naughty-cray
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31247
  type:  NodePort
